// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbztcPYQbWSYKz69U_I4rciNSTfdO_sRw',
    appId: '1:843206674848:web:cf235cc1191e4e7b97fcc5',
    messagingSenderId: '843206674848',
    projectId: 'taskify-5f586',
    authDomain: 'taskify-5f586.firebaseapp.com',
    storageBucket: 'taskify-5f586.appspot.com',
    measurementId: 'G-K4JSLJ8SKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5uN1FkOjNmNUOzZIqnskiFZ-nRLF21GU',
    appId: '1:843206674848:android:4376ebcb6712eabe97fcc5',
    messagingSenderId: '843206674848',
    projectId: 'taskify-5f586',
    storageBucket: 'taskify-5f586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-CarYa-DfqGyYtL6rTapCKCn_9Ol37I',
    appId: '1:843206674848:ios:010c0bed699ab5b197fcc5',
    messagingSenderId: '843206674848',
    projectId: 'taskify-5f586',
    storageBucket: 'taskify-5f586.appspot.com',
    iosBundleId: 'com.example.todoey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm-CarYa-DfqGyYtL6rTapCKCn_9Ol37I',
    appId: '1:843206674848:ios:010c0bed699ab5b197fcc5',
    messagingSenderId: '843206674848',
    projectId: 'taskify-5f586',
    storageBucket: 'taskify-5f586.appspot.com',
    iosBundleId: 'com.example.todoey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbztcPYQbWSYKz69U_I4rciNSTfdO_sRw',
    appId: '1:843206674848:web:0f3511d346ff0aa597fcc5',
    messagingSenderId: '843206674848',
    projectId: 'taskify-5f586',
    authDomain: 'taskify-5f586.firebaseapp.com',
    storageBucket: 'taskify-5f586.appspot.com',
    measurementId: 'G-F2X43P735B',
  );
}
